namespace POS.Domain.Entities;
public class UnitOfMeasure{public Guid Id{get;set;}public string Name{get;set;}=string.Empty;public string Symbol{get;set;}=string.Empty;public bool IsBase{get;set;}}
public class Ingredient{public Guid Id{get;set;}public string NameAr{get;set;}=string.Empty;public string NameEn{get;set;}=string.Empty;public Guid UnitOfMeasureId{get;set;}public UnitOfMeasure UnitOfMeasure{get;set;}=null!;}
public class Warehouse{public Guid Id{get;set;}public Guid BranchId{get;set;}public Branch Branch{get;set;}=null!;public string NameAr{get;set;}=string.Empty;public string NameEn{get;set;}=string.Empty;public bool IsDefault{get;set;}public bool IsActive{get;set;}=true;}
public class WarehouseIngredientStock{public Guid WarehouseId{get;set;}public Warehouse Warehouse{get;set;}=null!;public Guid IngredientId{get;set;}public Ingredient Ingredient{get;set;}=null!;public decimal CurrentQuantity{get;set;}public decimal LowStockThreshold{get;set;}}
public class MenuItemRecipeLine{public Guid Id{get;set;}public Guid MenuItemId{get;set;}public MenuItem MenuItem{get;set;}=null!;public Guid BranchId{get;set;}public Branch Branch{get;set;}=null!;public Guid IngredientId{get;set;}public Ingredient Ingredient{get;set;}=null!;public decimal QuantityRequired{get;set;}}
public class InventoryTransactionReason{public Guid Id{get;set;}public string Code{get;set;}=string.Empty;public string NameAr{get;set;}=string.Empty;public string NameEn{get;set;}=string.Empty;public bool IsActive{get;set;}=true;}
public class RestaurantInventoryTransaction{public Guid Id{get;set;}public Guid WarehouseId{get;set;}public Warehouse Warehouse{get;set;}=null!;public Guid IngredientId{get;set;}public Ingredient Ingredient{get;set;}=null!;public decimal QuantityChange{get;set;}public Guid ReasonId{get;set;}public InventoryTransactionReason Reason{get;set;}=null!;public Guid? ReferenceOrderId{get;set;}public RestaurantOrder? ReferenceOrder{get;set;}public Guid? CreatedByUserId{get;set;}public DateTime CreatedAt{get;set;}}
public static class StockCountStatuses{public const string Draft="Draft",Finalized="Finalized";}
public class StockCount{public Guid Id{get;set;}public Guid BranchId{get;set;}public Branch Branch{get;set;}=null!;public Guid WarehouseId{get;set;}public Warehouse Warehouse{get;set;}=null!;public Guid CountedByUserId{get;set;}public DateTime CreatedAt{get;set;}public string Status{get;set;}=StockCountStatuses.Draft;public ICollection<StockCountLine> Lines{get;set;}=[];}
public class StockCountLine{public Guid StockCountId{get;set;}public StockCount StockCount{get;set;}=null!;public Guid IngredientId{get;set;}public Ingredient Ingredient{get;set;}=null!;public decimal SystemQuantity{get;set;}public decimal CountedQuantity{get;set;}public decimal VarianceQuantity{get;set;}}
