namespace POS.Application.Payments;
public record PaymentMethodDto(Guid Id,string Code,string NameAr,string NameEn,bool RequiresApproval,bool IsActive);
public record OrderPaymentDto(Guid Id,Guid OrderId,string MethodCode,decimal Amount,Guid? ApprovedByUserId,DateTime CreatedAt,string OrderStatus,decimal GrandTotal,Guid? BillSplitId);
public record RecordOrderPaymentRequest(string PaymentMethodCode,decimal Amount,Guid? BillSplitId=null);
public record BillSplitLineRequest(Guid OrderItemId,int Quantity);
public record CreateEqualBillSplitsRequest(int ShareCount);
public record CreateItemBillSplitRequest(string? Name,List<BillSplitLineRequest> Lines);
public record BillSplitLineDto(Guid OrderItemId,string ItemName,int Quantity);
public record BillSplitDto(Guid Id,Guid OrderId,string Name,decimal Amount,decimal PaidAmount,decimal RemainingAmount,DateTime CreatedAt,List<BillSplitLineDto> Lines);
public record EditClosedOrderRequest(string EditType,decimal AmountDelta,string? Notes);
public record OrderEditLogDto(Guid Id,Guid OrderId,Guid UserId,string EditType,string? Notes,decimal AmountDelta,DateTime CreatedAt,decimal OrderGrandTotal);
