using System.Security.Cryptography;
using Microsoft.EntityFrameworkCore;
using POS.Application.Abstractions;
using POS.Application.Common;
using POS.Application.Orders;
using POS.Application.Printing;
using POS.Domain.Entities;
namespace POS.Application.QrOrdering;

public class QrOrderingService(IAppDbContext db, OrderPrintingService printing)
{
    public Task<List<CarPickupBayDto>> GetBaysAsync(Guid branchId, CancellationToken ct = default) => db.CarPickupBays.Where(x => x.BranchId == branchId).OrderBy(x => x.BayLabel).Select(x => new CarPickupBayDto(x.Id, x.BranchId, x.BayLabel, x.IsActive)).ToListAsync(ct);
    public Task<List<OrderingPointDto>> GetPointsAsync(Guid branchId, CancellationToken ct = default) => db.OrderingPoints.Where(x => x.BranchId == branchId).OrderBy(x => x.PointType).Select(x => new OrderingPointDto(x.Id, x.BranchId, x.PointType, x.LinkedTableId, x.LinkedCarBayId, x.QrCodeToken, x.IsActive, x.LinkedTable != null ? x.LinkedTable.Label : x.LinkedCarBay!.BayLabel, x.Sessions.Where(s => s.Status == OrderingSessionStatuses.Open).Select(s => (Guid?)s.Id).FirstOrDefault())).ToListAsync(ct);
    public async Task<CarPickupBayDto> SaveBayAsync(Guid? id, SaveCarPickupBayRequest r, CancellationToken ct = default) { if (string.IsNullOrWhiteSpace(r.BayLabel)) throw new ValidationException("Bay label is required."); var x = id is null ? new CarPickupBay { Id = Guid.NewGuid() } : await db.CarPickupBays.FirstOrDefaultAsync(x => x.Id == id, ct) ?? throw new NotFoundException("Car bay not found."); if (id is null) db.CarPickupBays.Add(x); x.BranchId = r.BranchId; x.BayLabel = r.BayLabel.Trim(); x.IsActive = r.IsActive; await db.SaveChangesAsync(ct); return new(x.Id, x.BranchId, x.BayLabel, x.IsActive); }
    public async Task<OrderingPointDto> SavePointAsync(Guid? id, SaveOrderingPointRequest r, CancellationToken ct = default) { ValidatePoint(r); if (r.PointType == OrderingPointTypes.Table && !await db.RestaurantTables.AnyAsync(x => x.Id == r.LinkedTableId && x.BranchId == r.BranchId, ct)) throw new ValidationException("Table is invalid for this branch."); if (r.PointType == OrderingPointTypes.CarBay && !await db.CarPickupBays.AnyAsync(x => x.Id == r.LinkedCarBayId && x.BranchId == r.BranchId, ct)) throw new ValidationException("Car bay is invalid for this branch."); var x = id is null ? new OrderingPoint { Id = Guid.NewGuid(), QrCodeToken = Token() } : await db.OrderingPoints.FirstOrDefaultAsync(x => x.Id == id, ct) ?? throw new NotFoundException("Ordering point not found."); if (id is null) db.OrderingPoints.Add(x); x.BranchId = r.BranchId; x.PointType = r.PointType; x.LinkedTableId = r.LinkedTableId; x.LinkedCarBayId = r.LinkedCarBayId; x.IsActive = r.IsActive; await db.SaveChangesAsync(ct); var label = r.PointType == OrderingPointTypes.Table ? (await db.RestaurantTables.FirstAsync(t => t.Id == r.LinkedTableId, ct)).Label : (await db.CarPickupBays.FirstAsync(b => b.Id == r.LinkedCarBayId, ct)).BayLabel; return new(x.Id, x.BranchId, x.PointType, x.LinkedTableId, x.LinkedCarBayId, x.QrCodeToken, x.IsActive, label, null); }
    public async Task<string> RegenerateAsync(Guid id, CancellationToken ct = default) { var x = await db.OrderingPoints.FirstOrDefaultAsync(x => x.Id == id, ct) ?? throw new NotFoundException("Ordering point not found."); if (await db.OrderingSessions.AnyAsync(s => s.OrderingPointId == id && s.Status == OrderingSessionStatuses.Open, ct)) throw new ValidationException("Close the active session before regenerating its QR code."); x.QrCodeToken = Token(); await db.SaveChangesAsync(ct); return x.QrCodeToken; }
    public async Task<QrSessionDto> ResolveAsync(string token, CancellationToken ct = default) { var point = await db.OrderingPoints.Include(x => x.LinkedTable).Include(x => x.LinkedCarBay).FirstOrDefaultAsync(x => x.QrCodeToken == token && x.IsActive, ct) ?? throw new NotFoundException("QR code is invalid or disabled."); var session = await db.OrderingSessions.FirstOrDefaultAsync(x => x.OrderingPointId == point.Id && x.Status == OrderingSessionStatuses.Open, ct); if (session is null) { session = new() { Id = Guid.NewGuid(), OrderingPointId = point.Id, Status = OrderingSessionStatuses.Open, OpenedAt = DateTime.UtcNow }; db.OrderingSessions.Add(session); try { await db.SaveChangesAsync(ct); } catch (DbUpdateException) { db.OrderingSessions.Remove(session); session = await db.OrderingSessions.FirstAsync(x => x.OrderingPointId == point.Id && x.Status == OrderingSessionStatuses.Open, ct); } } return Session(point, session); }
    public async Task<RestaurantOrderDto> AddAsync(Guid sessionId, AddQrOrderRequest r, CancellationToken ct = default) { if (r.Lines.Count == 0 || r.Lines.Any(x => x.Quantity <= 0)) throw new ValidationException("Order needs positive lines."); var session = await db.OrderingSessions.Include(x => x.OrderingPoint).ThenInclude(x => x.LinkedTable).Include(x => x.OrderingPoint).ThenInclude(x => x.LinkedCarBay).FirstOrDefaultAsync(x => x.Id == sessionId && x.Status == OrderingSessionStatuses.Open, ct) ?? throw new NotFoundException("Open ordering session not found."); var point = session.OrderingPoint; var code = r.SalesChannelCode.Trim().ToUpperInvariant(); var availability = await db.BranchSalesChannelAvailabilities.Include(x => x.SalesChannel).FirstOrDefaultAsync(x => x.BranchId == point.BranchId && x.SalesChannel.Code == code && x.SalesChannel.IsActive && x.IsEnabled, ct) ?? throw new ValidationException("Sales channel is unavailable at this branch."); var typeCode = point.PointType == OrderingPointTypes.Table ? "DINE_IN" : "CAR_PICKUP"; var type = await db.OrderTypes.FirstAsync(x => x.Code == typeCode, ct); var order = await db.RestaurantOrders.Include(x => x.Items).ThenInclude(x => x.Modifiers).Include(x => x.Items).ThenInclude(x => x.ComboSelections).FirstOrDefaultAsync(x => x.OrderingSessionId == sessionId && x.Status == RestaurantOrderStatuses.Open, ct); if (order is null) { order = new() { Id = Guid.NewGuid(), BranchId = point.BranchId, OrderNumber = await db.ClaimNextOrderNumberAsync(point.BranchId, ct), OrderTypeId = type.Id, TableId = point.LinkedTableId, CarPlateNumber = point.LinkedCarBay?.BayLabel, SalesChannelId = availability.SalesChannelId, OrderingSessionId = sessionId, BusinessDate = DateOnly.FromDateTime(DateTime.UtcNow), CreatedAt = DateTime.UtcNow, Status = RestaurantOrderStatuses.Open }; db.RestaurantOrders.Add(order); } await AddLines(order, r.Lines, ct); order.Subtotal = order.Items.Where(x => !x.IsCancelled).Sum(x => x.LineTotal); order.GrandTotal = order.Subtotal - order.DiscountAmount; await db.SaveChangesAsync(ct); return new(order.Id, order.BranchId, order.OrderNumber, type.Code, order.TableId, point.LinkedTable?.Label, order.Status, order.Subtotal, order.DiscountAmount, order.GrandTotal, order.CreatedAt, order.Items.Select(i => new OrderLineDto(i.Id, i.MenuItemId, i.MenuItemNameSnapshot, i.UnitPriceSnapshot, i.Quantity, i.LineTotal, i.Notes, i.IsCancelled, i.Modifiers.Select(m => m.ModifierOptionId).ToList(), i.ComboSelections.Select(c => c.SelectedMenuItemId).ToList())).ToList()); }
    public async Task ConfirmAsync(Guid orderId, CancellationToken ct = default) { var order = await db.RestaurantOrders.Include(x => x.Payments).FirstOrDefaultAsync(x => x.Id == orderId && x.OrderingSessionId != null, ct) ?? throw new NotFoundException("QR order not found."); var cfg = await db.BranchSalesChannelAvailabilities.FirstOrDefaultAsync(x => x.BranchId == order.BranchId && x.SalesChannelId == order.SalesChannelId, ct) ?? throw new ValidationException("Channel configuration is missing."); if (cfg.RequiresPrepayment && order.Payments.Sum(x => x.Amount) < order.GrandTotal) throw new ValidationException("Full prepayment is required before confirmation."); await printing.ConfirmAndPrintAsync(orderId, ct); }
    public async Task CloseAsync(Guid sessionId, CancellationToken ct = default) { var s = await db.OrderingSessions.Include(x => x.OrderingPoint).FirstOrDefaultAsync(x => x.Id == sessionId && x.Status == OrderingSessionStatuses.Open, ct) ?? throw new NotFoundException("Open session not found."); var order = await db.RestaurantOrders.FirstOrDefaultAsync(x => x.OrderingSessionId == sessionId, ct); if (order is not null && order.Status is not (RestaurantOrderStatuses.Paid or RestaurantOrderStatuses.Closed)) throw new ValidationException("The invoice must be fully settled before closing the session."); s.Status = OrderingSessionStatuses.Closed; s.ClosedAt = DateTime.UtcNow; s.OrderingPoint.QrCodeToken = Token(); await db.SaveChangesAsync(ct); }
    private async Task AddLines(RestaurantOrder order, List<CreateOrderLineRequest> inputs, CancellationToken ct) { var ids = inputs.Select(x => x.MenuItemId).Distinct().ToList(); var items = await db.MenuItems.Where(x => ids.Contains(x.Id) && x.IsActive).Include(x => x.ModifierGroups).ThenInclude(x => x.ModifierGroup).ThenInclude(x => x.Options).Include(x => x.ComboComponents).ThenInclude(x => x.Options).ToDictionaryAsync(x => x.Id, ct); if (items.Count != ids.Count) throw new ValidationException("Menu item unavailable."); foreach (var input in inputs) { var item = items[input.MenuItemId]; decimal delta = 0; var line = new RestaurantOrderItem { Id = Guid.NewGuid(), MenuItemId = item.Id, MenuItemNameSnapshot = item.NameEn, Quantity = input.Quantity, Notes = input.Notes?.Trim() }; if (item.Kind == MenuItemKinds.SingleProduct) { var selected = input.ModifierOptionIds.Distinct().ToList(); foreach (var link in item.ModifierGroups) { var group = link.ModifierGroup; var chosen = group.Options.Where(x => selected.Contains(x.Id) && x.IsActive).ToList(); var min = group.IsRequired ? Math.Max(1, group.MinSelect) : group.MinSelect; if (chosen.Count < min || chosen.Count > group.MaxSelect) throw new ValidationException($"Invalid selection for {group.NameEn}."); foreach (var o in chosen) { delta += o.PriceDelta; line.Modifiers.Add(new() { Id = Guid.NewGuid(), ModifierOptionId = o.Id, PriceDeltaSnapshot = o.PriceDelta }); } } if (selected.Any(x => !line.Modifiers.Any(m => m.ModifierOptionId == x))) throw new ValidationException("Modifier unavailable."); } else foreach (var c in item.ComboComponents) { var chosen = input.ComboSelections.Where(x => x.ComboComponentId == c.Id).ToList(); var min = c.IsRequired ? Math.Max(1, c.MinSelect) : c.MinSelect; if (chosen.Count < min || chosen.Count > c.MaxSelect) throw new ValidationException($"Invalid selection for {c.SlotLabel}."); foreach (var s in chosen) { var o = c.Options.SingleOrDefault(x => x.MenuItemId == s.SelectedMenuItemId) ?? throw new ValidationException("Combo option unavailable."); delta += o.PriceDelta; line.ComboSelections.Add(new() { Id = Guid.NewGuid(), ComboComponentId = c.Id, SelectedMenuItemId = o.MenuItemId, PriceDeltaSnapshot = o.PriceDelta }); } } line.UnitPriceSnapshot = item.BasePrice + delta; line.LineTotal = line.UnitPriceSnapshot * line.Quantity; order.Items.Add(line); db.RestaurantOrderItems.Add(line); } }
    private static void ValidatePoint(SaveOrderingPointRequest r) { if (!OrderingPointTypes.All.Contains(r.PointType) || (r.PointType == OrderingPointTypes.Table) != (r.LinkedTableId is not null) || (r.PointType == OrderingPointTypes.CarBay) != (r.LinkedCarBayId is not null)) throw new ValidationException("Ordering point link does not match its type."); }
    private static string Token() => Convert.ToBase64String(RandomNumberGenerator.GetBytes(32)).Replace('+', '-').Replace('/', '_').TrimEnd('='); private static QrSessionDto Session(OrderingPoint p, OrderingSession s) => new(s.Id, p.Id, p.BranchId, p.PointType, p.LinkedTable?.Label ?? p.LinkedCarBay!.BayLabel, s.OpenedAt);
}
