import { FormEvent, useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { api, ApiError } from '../api/client';
import type { BranchDto, MenuItemDto, PrinterConfigDto, PrinterSectionDto } from '../api/types';
import { useToast } from '../components/ToastContext';

export default function PrintersPage() {
  const { t, i18n } = useTranslation(); const toast = useToast();
  const [branches,setBranches]=useState<BranchDto[]>([]),[branchId,setBranchId]=useState(''),[printers,setPrinters]=useState<PrinterConfigDto[]>([]),[sections,setSections]=useState<PrinterSectionDto[]>([]),[items,setItems]=useState<MenuItemDto[]>([]);
  const [printer,setPrinter]=useState({nameAr:'',nameEn:'',ipAddress:'',port:9100,isDefault:false,isActive:true}); const [section,setSection]=useState({nameAr:'',nameEn:'',printerConfigId:''});
  const name=(x:{nameAr:string;nameEn:string})=>i18n.language==='ar'?x.nameAr:x.nameEn;
  const load=async(id:string)=>{const[p,s,m]=await Promise.all([api.get<PrinterConfigDto[]>(`/api/printers?branchId=${id}`),api.get<PrinterSectionDto[]>(`/api/printers/sections?branchId=${id}`),api.get<MenuItemDto[]>('/api/restaurant-catalog/items')]);setPrinters(p);setSections(s);setItems(m)};
  useEffect(()=>{void api.get<BranchDto[]>('/api/branches').then(x=>{setBranches(x);setBranchId(x[0]?.id??'')})},[]); useEffect(()=>{if(branchId)void load(branchId)},[branchId]);
  const savePrinter=async(e:FormEvent)=>{e.preventDefault();try{await api.post('/api/printers',{branchId,...printer});setPrinter({nameAr:'',nameEn:'',ipAddress:'',port:9100,isDefault:false,isActive:true});await load(branchId);toast.success(t('printers.saved'))}catch(error){toast.error(error instanceof ApiError?error.message:t('common.saveError'))}};
  const saveSection=async(e:FormEvent)=>{e.preventDefault();try{await api.post('/api/printers/sections',{branchId,...section,printerConfigId:section.printerConfigId||null});setSection({nameAr:'',nameEn:'',printerConfigId:''});await load(branchId);toast.success(t('printers.saved'))}catch(error){toast.error(error instanceof ApiError?error.message:t('common.saveError'))}};
  const assign=async(item:MenuItemDto,printerSectionId:string)=>{try{await api.put(`/api/restaurant-catalog/items/${item.id}`,{...item,printerSectionId:printerSectionId||null});setItems(x=>x.map(y=>y.id===item.id?{...y,printerSectionId:printerSectionId||null}:y));toast.success(t('printers.saved'))}catch(error){toast.error(error instanceof ApiError?error.message:t('common.saveError'))}};
  return <section><h1>{t('printers.title')}</h1><div className="table-toolbar"><select value={branchId} onChange={e=>setBranchId(e.target.value)}>{branches.map(x=><option key={x.id} value={x.id}>{name(x)}</option>)}</select></div><div className="grid gap-6 lg:grid-cols-2"><form className="settings-card" onSubmit={savePrinter}><h2>{t('printers.addPrinter')}</h2><input required value={printer.nameAr} onChange={e=>setPrinter({...printer,nameAr:e.target.value})} placeholder={t('common.nameAr')}/><input required value={printer.nameEn} onChange={e=>setPrinter({...printer,nameEn:e.target.value})} placeholder={t('common.nameEn')}/><input required value={printer.ipAddress} onChange={e=>setPrinter({...printer,ipAddress:e.target.value})} placeholder={t('printers.address')}/><input type="number" min="1" max="65535" value={printer.port} onChange={e=>setPrinter({...printer,port:Number(e.target.value)})}/><label className="checkbox-row"><input type="checkbox" checked={printer.isDefault} onChange={e=>setPrinter({...printer,isDefault:e.target.checked})}/>{t('printers.default')}</label><button>{t('common.save')}</button>{printers.map(x=><div className="table-toolbar" key={x.id}><span>{name(x)} · {x.ipAddress}:{x.port}</span><button type="button" onClick={()=>api.post(`/api/printers/${x.id}/test`,{text:'OFC printer test'}).then(()=>toast.success(t('printers.testSent'))).catch(()=>toast.error(t('common.saveError')))}>{t('printers.test')}</button></div>)}</form><form className="settings-card" onSubmit={saveSection}><h2>{t('printers.addSection')}</h2><input required value={section.nameAr} onChange={e=>setSection({...section,nameAr:e.target.value})} placeholder={t('common.nameAr')}/><input required value={section.nameEn} onChange={e=>setSection({...section,nameEn:e.target.value})} placeholder={t('common.nameEn')}/><select value={section.printerConfigId} onChange={e=>setSection({...section,printerConfigId:e.target.value})}><option value="">{t('printers.default')}</option>{printers.map(x=><option key={x.id} value={x.id}>{name(x)}</option>)}</select><button>{t('common.save')}</button>{sections.map(x=><div key={x.id}>{name(x)}</div>)}</form></div><div className="settings-card"><h2>{t('printers.routing')}</h2>{items.map(item=><label className="table-toolbar" key={item.id}><span>{name(item)}</span><select value={item.printerSectionId??''} onChange={e=>void assign(item,e.target.value)}><option value="">{t('printers.default')}</option>{sections.map(x=><option key={x.id} value={x.id}>{name(x)}</option>)}</select></label>)}</div></section>;
}
