using Microsoft.EntityFrameworkCore;using POS.Application.Abstractions;using POS.Application.CashShifts;using POS.Application.Common;using POS.Domain.Constants;using POS.Domain.Entities;using POS.Infrastructure.Persistence;using Xunit;
namespace POS.Application.Tests;public class CashShiftTests
{
 [Fact]public async Task Close_calculates_expected_counted_and_variance(){await using var db=Db();var branch=Guid.NewGuid();var user=new User([PermissionKeys.SalesEdit]);var service=new CashShiftService(db,user);var shift=await service.OpenAsync(new(branch,5),TestContext.Current.CancellationToken);var cash=await db.PaymentMethods.SingleAsync(x=>x.Code=="CASH",TestContext.Current.CancellationToken);var order=new RestaurantOrder{Id=Guid.NewGuid(),BranchId=branch,CashShiftId=shift.Id};db.RestaurantOrders.Add(order);db.OrderPayments.Add(new(){Id=Guid.NewGuid(),Order=order,PaymentMethodId=cash.Id,Amount=7});await db.SaveChangesAsync(TestContext.Current.CancellationToken);var closed=await service.CloseAsync(shift.Id,new([new(10,"Note",1),new(1,"Note",1)]),TestContext.Current.CancellationToken);Assert.Equal(12,closed.ExpectedCash);Assert.Equal(11,closed.CountedCash);Assert.Equal(-1,closed.VarianceCash);}
 [Fact]public void Empty_count_is_rejected()=>Assert.Throws<ValidationException>(()=>CashShiftService.ValidateCounts([]));
 [Fact]public async Task User_without_permission_cannot_open(){await using var db=Db();await Assert.ThrowsAsync<ForbiddenException>(()=>new CashShiftService(db,new User([])).OpenAsync(new(Guid.NewGuid(),0),TestContext.Current.CancellationToken));}
 private static AppDbContext Db(){var db=new AppDbContext(new DbContextOptionsBuilder<AppDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options);db.Database.EnsureCreated();return db;}
 private sealed class User(IReadOnlyCollection<string> p):ICurrentUserService{public Guid? UserId{get;}=Guid.NewGuid();public Guid? BranchId=>null;public string? RoleName=>"Manager";public IReadOnlyCollection<string> Permissions=>p;public bool BypassBranchFilter=>true;}
}
