using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using POS.Application.Abstractions;
using POS.Application.Common;
using POS.Application.Printing;
using POS.Application.QrOrdering;
using POS.Domain.Entities;
using POS.Infrastructure.Persistence;
using Xunit;
namespace POS.Application.Tests;

public class QrOrderingTests
{
    [Fact] public async Task Two_scans_join_the_same_open_session() { await using var db = Db(); var p = Point(db, "TABLE", "T1"); var service = Service(db); var a = await service.ResolveAsync(p.QrCodeToken, TestContext.Current.CancellationToken); var b = await service.ResolveAsync(p.QrCodeToken, TestContext.Current.CancellationToken); Assert.Equal(a.SessionId, b.SessionId); Assert.Single(db.OrderingSessions); }
    [Fact] public async Task Car_bay_scan_returns_car_bay_label() { await using var db = Db(); var p = Point(db, "CAR_BAY", "Bay 3"); var result = await Service(db).ResolveAsync(p.QrCodeToken, TestContext.Current.CancellationToken); Assert.Equal("CAR_BAY", result.PointType); Assert.Equal("Bay 3", result.Label); }
    [Fact] public async Task Prepayment_rule_rejects_unpaid_confirmation() { await using var db = Db(); var channel = new SalesChannel { Id = Guid.NewGuid(), Code = "QR_TABLE", NameAr = "QR", NameEn = "QR" }; var order = new RestaurantOrder { Id = Guid.NewGuid(), BranchId = Guid.NewGuid(), OrderingSessionId = Guid.NewGuid(), SalesChannelId = channel.Id, GrandTotal = 5, Status = RestaurantOrderStatuses.Open }; db.SalesChannels.Add(channel); db.RestaurantOrders.Add(order); db.BranchSalesChannelAvailabilities.Add(new() { Id = Guid.NewGuid(), BranchId = order.BranchId, SalesChannelId = channel.Id, RequiresPrepayment = true, IsEnabled = true }); await db.SaveChangesAsync(TestContext.Current.CancellationToken); await Assert.ThrowsAsync<ValidationException>(() => Service(db).ConfirmAsync(order.Id, TestContext.Current.CancellationToken)); }
    [Fact] public async Task Repeated_additions_join_one_session_invoice() { var root = new InMemoryDatabaseRoot(); var options = new DbContextOptionsBuilder<AppDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString(), root).Options; Guid session; Guid itemId; await using (var seed = Db(options)) { var point = Point(seed, "TABLE", "T1"); session = (await Service(seed).ResolveAsync(point.QrCodeToken, TestContext.Current.CancellationToken)).SessionId; var channel = new SalesChannel { Id = Guid.NewGuid(), Code = "QR_TABLE", NameAr = "QR", NameEn = "QR" }; var category = new MenuCategory { Id = Guid.NewGuid(), NameAr = "ق", NameEn = "C" }; var item = new MenuItem { Id = Guid.NewGuid(), Category = category, NameAr = "ص", NameEn = "Item", BasePrice = 2 }; itemId = item.Id; seed.AddRange(channel, category, item); seed.BranchSalesChannelAvailabilities.Add(new() { Id = Guid.NewGuid(), BranchId = point.BranchId, SalesChannel = channel, IsEnabled = true }); var type = await seed.OrderTypes.SingleAsync(x => x.Code == "DINE_IN", TestContext.Current.CancellationToken); seed.RestaurantOrders.Add(new() { Id = Guid.NewGuid(), BranchId = point.BranchId, OrderNumber = 1, OrderTypeId = type.Id, TableId = point.LinkedTableId, SalesChannelId = channel.Id, OrderingSessionId = session, Status = RestaurantOrderStatuses.Open }); await seed.SaveChangesAsync(TestContext.Current.CancellationToken); } var request = new AddQrOrderRequest("QR_TABLE", [new(itemId, 1, null, [], [])]); await using (var first = Db(options)) await Service(first).AddAsync(session, request, TestContext.Current.CancellationToken); await using (var second = Db(options)) await Service(second).AddAsync(session, request, TestContext.Current.CancellationToken); await using var verify = Db(options); Assert.Single(verify.RestaurantOrders); Assert.Equal(2, verify.RestaurantOrderItems.Count()); Assert.Equal(4, (await verify.RestaurantOrders.SingleAsync(TestContext.Current.CancellationToken)).GrandTotal); }
    [Fact] public async Task Closing_paid_session_rotates_token() { await using var db = Db(); var p = Point(db, "TABLE", "T1"); var service = Service(db); var session = await service.ResolveAsync(p.QrCodeToken, TestContext.Current.CancellationToken); db.RestaurantOrders.Add(new() { Id = Guid.NewGuid(), OrderingSessionId = session.SessionId, Status = RestaurantOrderStatuses.Paid }); await db.SaveChangesAsync(TestContext.Current.CancellationToken); var old = p.QrCodeToken; await service.CloseAsync(session.SessionId, TestContext.Current.CancellationToken); Assert.NotEqual(old, p.QrCodeToken); Assert.Equal(OrderingSessionStatuses.Closed, db.OrderingSessions.Single().Status); }
    private static AppDbContext Db() { return Db(new DbContextOptionsBuilder<AppDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options); }
    private static AppDbContext Db(DbContextOptions<AppDbContext> options) { var db = new AppDbContext(options); db.Database.EnsureCreated(); return db; }
    private static QrOrderingService Service(AppDbContext db) => new(db, new OrderPrintingService(db, new Printer()));
    private static OrderingPoint Point(AppDbContext db, string type, string label) { var branch = Guid.NewGuid(); var p = new OrderingPoint { Id = Guid.NewGuid(), BranchId = branch, PointType = type, QrCodeToken = Guid.NewGuid().ToString("N"), IsActive = true }; if (type == OrderingPointTypes.Table) { var t = new RestaurantTable { Id = Guid.NewGuid(), BranchId = branch, Label = label }; db.RestaurantTables.Add(t); p.LinkedTable = t; p.LinkedTableId = t.Id; } else { var b = new CarPickupBay { Id = Guid.NewGuid(), BranchId = branch, BayLabel = label }; db.CarPickupBays.Add(b); p.LinkedCarBay = b; p.LinkedCarBayId = b.Id; } db.OrderingPoints.Add(p); db.SaveChanges(); return p; }
    private sealed class Printer : IRawPrinterClient { public Task SendAsync(string ipAddress, int port, byte[] payload, CancellationToken cancellationToken = default) => Task.CompletedTask; }
}
