using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.AspNetCore.SignalR;using POS.API.Authorization;using POS.API.Hubs;using POS.Application.Orders;using POS.Application.Printing;using POS.Application.QrOrdering;using POS.Application.Invoices;using POS.Domain.Constants;
namespace POS.API.Controllers;
[ApiController,Route("api/restaurant-orders"),Authorize]
public class RestaurantOrdersController(RestaurantOrderService service,OrderCancellationService cancellations,OrderPrintingService printing,QrOrderingService qr,InvoiceService invoices,IHubContext<RestaurantOrdersHub> staffHub,IHubContext<QrOrdersHub> qrHub):ControllerBase
{
 [HttpGet("types")]public async Task<ActionResult<List<OrderTypeDto>>>Types(CancellationToken ct)=>Ok(await service.GetTypesAsync(ct));
 [HttpGet]public async Task<ActionResult<List<RestaurantOrderDto>>>Get([FromQuery]Guid branchId,CancellationToken ct)=>Ok(await service.GetAsync(branchId,ct));
 [HttpPost,RequirePermission(PermissionKeys.OrdersCreate)]public async Task<ActionResult<RestaurantOrderDto>>Create(CreateRestaurantOrderRequest request,CancellationToken ct)=>Ok(await service.CreateAsync(request,ct));
 [HttpPost("{orderId:guid}/confirm"),RequirePermission(PermissionKeys.OrdersCreate)]public async Task<IActionResult>Confirm(Guid orderId,CancellationToken ct){await printing.ConfirmAndPrintAsync(orderId,ct);return NoContent();}
 [HttpPost("{orderId:guid}/approve-qr"),RequirePermission(PermissionKeys.OrdersCreate)]public async Task<ActionResult<RestaurantOrderDto>>ApproveQr(Guid orderId,CancellationToken ct){await qr.ApproveAsync(orderId,ct);var order=await service.GetByIdAsync(orderId,ct);await Publish(order,"QrOrderApproved",ct);return Ok(order);}
 [HttpPost("{orderId:guid}/reject-qr"),RequirePermission(PermissionKeys.OrdersCreate)]public async Task<ActionResult<RestaurantOrderDto>>RejectQr(Guid orderId,RejectQrOrderRequest request,CancellationToken ct){await qr.RejectAsync(orderId,request.Reason,ct);var order=await service.GetByIdAsync(orderId,ct);await Publish(order,"QrOrderRejected",ct);return Ok(order);}
 [HttpPut("{orderId:guid}/pending-qr"),RequirePermission(PermissionKeys.OrdersCreate)]public async Task<ActionResult<RestaurantOrderDto>>EditQr(Guid orderId,EditPendingQrOrderRequest request,CancellationToken ct){var order=await qr.EditPendingAsync(orderId,request,ct);await Publish(order,"QrOrderUpdated",ct);return Ok(order);}
 [HttpPost("{orderId:guid}/items/{itemId:guid}/cancel"),RequirePermission(PermissionKeys.OrdersCancel)]public async Task<IActionResult>CancelItem(Guid orderId,Guid itemId,CancelOrderRequest request,CancellationToken ct){await cancellations.CancelItemAsync(orderId,itemId,request.Reason,ct);return NoContent();}
 [HttpPost("{orderId:guid}/cancel"),RequirePermission(PermissionKeys.OrdersCancel)]public async Task<IActionResult>CancelOrder(Guid orderId,CancelOrderRequest request,CancellationToken ct){await cancellations.CancelOrderAsync(orderId,request.Reason,ct);return NoContent();}
 [HttpGet("{orderId:guid}/invoice")]public async Task<ActionResult<InvoiceDocument>>Invoice(Guid orderId,CancellationToken ct)=>Ok(await invoices.GetDocumentAsync(orderId,ct));
 [HttpGet("{orderId:guid}/invoice.pdf")]public async Task<IActionResult>InvoicePdf(Guid orderId,CancellationToken ct){var invoice=await invoices.GetDocumentAsync(orderId,ct);return File(invoices.CreatePdf(invoice),"application/pdf",$"invoice-{invoice.InvoiceNumber}.pdf");}
 [HttpPost("{orderId:guid}/invoice/print"),RequirePermission(PermissionKeys.OrdersCreate)]public async Task<IActionResult>PrintInvoice(Guid orderId,CancellationToken ct){await printing.PrintCustomerInvoiceAsync(orderId,ct);return NoContent();}
 [HttpGet("cancellations"),RequirePermission(PermissionKeys.OrdersCancel)]public async Task<ActionResult<List<OrderCancellationDto>>>CancellationLog([FromQuery]Guid branchId,[FromQuery]DateTime? from,[FromQuery]DateTime? to,[FromQuery]Guid? cashierUserId,CancellationToken ct)=>Ok(await cancellations.GetAsync(branchId,from,to,cashierUserId,ct));
 private async Task Publish(RestaurantOrderDto order,string eventName,CancellationToken ct){await staffHub.Clients.Group(RestaurantOrdersHub.BranchGroup(order.BranchId)).SendAsync(eventName,order,ct);var sessionId=await service.GetOrderingSessionIdAsync(order.Id,ct);if(sessionId.HasValue)await qrHub.Clients.Group(QrOrdersHub.SessionGroup(sessionId.Value)).SendAsync("QrOrderStatusChanged",order,ct);}
}
